# Generated by Django 6.0.2 on 2026-02-24 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='events.event'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.UniqueConstraint(fields=('booking', 'seat'), name='unique_seat_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('event', 'seat'), name='unique_active_seat_per_event'),
        ),
    ]
