# Generated by Django 6.0.2 on 2026-02-23 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('layout_meta', models.JSONField(blank=True, default=dict, help_text='Canvas metadata: width, height, background, decorative shapes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('cx', models.FloatField(help_text='X coordinate on canvas')),
                ('cy', models.FloatField(help_text='Y coordinate on canvas')),
                ('section', models.CharField(blank=True, default='', max_length=100)),
                ('row_label', models.CharField(blank=True, default='', max_length=50)),
                ('seat_number', models.IntegerField(default=0)),
                ('seat_type', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('balcony', 'Balcony')], default='regular', max_length=50)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.venue')),
            ],
            options={
                'ordering': ['section', 'row_label', 'seat_number'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('date', models.DateTimeField()),
                ('price_tiers', models.JSONField(blank=True, default=dict, help_text='Maps seat_type to price, e.g. {"vip": 50, "regular": 25}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.venue')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
