# Generated by Django 6.0.2 on 2026-02-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(default='regular', max_length=50),
        ),
    ]
