from django.db import models


class BookingStatus(models.TextChoices):
    PENDING = 'pending', 'Pending'
    PAID = 'paid', 'Paid'
    CANCELLED = 'cancelled', 'Cancelled'


class SeatAvailabilityStatus:
    OPEN = 'open'
    BOOKED = 'booked'
    PAID = 'paid'


ROW_PRICE_PREFIX = 'row:'

ERROR_KEY = 'error'
VALID_KEY = 'valid'
CONSUMED_KEY = 'consumed'
CODE_KEY = 'code'
TAKEN_SEAT_IDS_KEY = 'taken_seat_ids'
MISSING_SEAT_TYPES_KEY = 'missing_seat_types'
TICKET_ID_KEY = 'ticket_id'
BOOKING_ID_KEY = 'booking_id'
PAYLOAD_KEY = 'payload'
SIGNATURE_KEY = 'sig'
EVENT_ID_KEY = 'event_id'
SEAT_IDS_KEY = 'seat_ids'
CUSTOMER_NAME_KEY = 'customer_name'
PHONE_NUMBER_KEY = 'phone_number'
VENUE_KEY = 'venue'
PRICE_TIERS_KEY = 'price_tiers'
SEATS_KEY = 'seats'
STATUS_KEY = 'status'
ID_KEY = 'id'
NAME_KEY = 'name'
LAYOUT_META_KEY = 'layout_meta'
SECTION_KEY = 'section'
ROW_KEY = 'row'
NUMBER_KEY = 'number'
TYPE_KEY = 'type'
BOOKING_KEY = 'booking'
EVENT_KEY = 'event'
EVENT_DATE_KEY = 'event_date'
TOTAL_PRICE_KEY = 'total_price'
SCANNED_AT_KEY = 'scanned_at'

INVALID_QR_CODE = 'INVALID_QR'
TICKET_NOT_FOUND_CODE = 'TICKET_NOT_FOUND'
BOOKING_CANCELLED_CODE = 'BOOKING_CANCELLED'
BOOKING_UNPAID_CODE = 'BOOKING_UNPAID'
TICKET_ALREADY_SCANNED_CODE = 'TICKET_ALREADY_SCANNED'
TICKET_SCANNED_ELSEWHERE_CODE = 'TICKET_SCANNED_ELSEWHERE'
EVENT_NOT_FOUND_CODE = 'EVENT_NOT_FOUND'
EVENT_NOT_FOUND_OR_INACTIVE_CODE = 'EVENT_NOT_FOUND_OR_INACTIVE'
SEATS_NOT_AVAILABLE_FOR_VENUE_CODE = 'SEATS_NOT_AVAILABLE_FOR_VENUE'
INVALID_PRICE_TIERS_CODE = 'INVALID_PRICE_TIERS'
MISSING_PRICE_TYPES_CODE = 'MISSING_PRICE_TYPES'
SEATS_ALREADY_BOOKED_CODE = 'SEATS_ALREADY_BOOKED'

INVALID_QR_MESSAGE = 'QR-код недействителен или поврежден.'
TICKET_NOT_FOUND_MESSAGE = 'Билет не найден.'
BOOKING_CANCELLED_MESSAGE = 'Эта бронь отменена.'
BOOKING_UNPAID_MESSAGE = 'Эта бронь еще не оплачена.'
TICKET_SCANNED_ELSEWHERE_MESSAGE = 'Билет только что был погашен на другом устройстве.'
EVENT_NOT_FOUND_OR_INACTIVE_MESSAGE = 'Событие не найдено или не активно.'
EVENT_NOT_FOUND_MESSAGE = 'Событие не найдено.'
SEATS_NOT_AVAILABLE_FOR_VENUE_MESSAGE = 'Одно или несколько мест недоступны для этой площадки.'
INVALID_PRICE_TIERS_MESSAGE = 'В тарифах события указаны некорректные значения.'
MISSING_PRICE_TYPES_MESSAGE = 'Для этого события не хватает цен по типам мест.'
SEATS_ALREADY_BOOKED_MESSAGE = 'Некоторые места уже забронированы.'
